# Applications
pp_security_applications_directory:
    pattern: /applications
    defaults: { _controller: PropertyPrivatelySecurityBundle:Applications:directory }
    methods: [GET]

pp_security_applications_get:
    pattern: /applications/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:Applications:get }
    methods: [GET]
    requirements:
        id: \d+

# Users
pp_security_users_get:
    pattern: /users/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:Users:get }
    methods: [GET]
    requirements:
        id: \d+

# User
pp_security_user_get:
    pattern: /user
    defaults: { _controller: PropertyPrivatelySecurityBundle:User:get }
    methods: [GET]

# User Applications
pp_security_user_applications_get_all:
    pattern: /user/applications
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserApplications:getAll }
    methods: [GET]

pp_security_user_applications_get:
    pattern: /user/applications/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserApplications:get }
    methods: [GET]
    requirements:
        id: \d+

# User Tokens
pp_security_user_tokens_get_all:
    pattern: /user/tokens
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:getAll }
    methods: [GET]

pp_security_user_tokens_get:
    pattern: /user/tokens/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:get }
    methods: [GET]
    requirements:
        id: \d+

pp_security_user_tokens_post:
    pattern: /user/tokens
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:post }
    methods: [POST]

pp_security_user_tokens_patch:
    pattern: /user/tokens/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:patch }
    methods: [PATCH]
    requirements:
        id: \d+

pp_security_user_tokens_delete_all:
    pattern: /user/tokens
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:deleteAll }
    methods: [DELETE]

pp_security_user_tokens_delete:
    pattern: /user/tokens/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:delete }
    methods: [DELETE]
    requirements:
        id: \d+

# User Tokens Application
pp_security_user_tokens_application_get_all:
    pattern: /user/tokens/application/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokensApplication:getAll }
    methods: [GET]
    requirements:
        id: \d+
