# Applications
pp_security_applications_directory:
    pattern: /applications
    defaults: { _controller: PropertyPrivatelySecurityBundle:Applications:directory }
    methods: [GET]

pp_security_applications_get:
    pattern: /applications/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:Applications:get }
    methods: [GET]
    requirements:
        id: \d+

pp_security_applications_post:
    pattern: /applications
    defaults: { _controller: PropertyPrivatelySecurityBundle:Applications:post }
    methods: [POST]

# Authentication
pp_security_authentication_post:
    pattern: /auth
    defaults: { _controller: PropertyPrivatelySecurityBundle:Authentication:post }
    methods: [POST]

# Users
pp_security_users_directory:
    pattern: /users
    defaults: { _controller: PropertyPrivatelySecurityBundle:Users:directory }
    methods: [GET]

pp_security_users_post:
    pattern: /users
    defaults: { _controller: PropertyPrivatelySecurityBundle:Users:post }
    methods: [POST]

pp_security_users_get:
    pattern: /users/{username}
    defaults: { _controller: PropertyPrivatelySecurityBundle:Users:get }
    methods: [GET]

# User
pp_security_user_get:
    pattern: /user
    defaults: { _controller: PropertyPrivatelySecurityBundle:User:get }
    methods: [GET]

pp_security_user_patch:
    pattern: /user
    defaults: { _controller: PropertyPrivatelySecurityBundle:User:patch }
    methods: [PATCH]

# User Applications
pp_security_user_applications_get_all:
    pattern: /user/applications
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserApplications:getAll }
    methods: [GET]

# User Tokens
pp_security_user_tokens_get_all:
    pattern: /user/tokens
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:getAll }
    methods: [GET]

pp_security_user_tokens_get:
    pattern: /user/tokens/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:get }
    methods: [GET]
    requirements:
        id: \d+

pp_security_user_tokens_patch:
    pattern: /user/tokens/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:patch }
    methods: [PATCH]
    requirements:
        id: \d+

pp_security_user_tokens_delete_all:
    pattern: /user/tokens
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:deleteAll }
    methods: [DELETE]

pp_security_user_tokens_delete:
    pattern: /user/tokens/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:delete }
    methods: [DELETE]
    requirements:
        id: \d+
