# Applications
pp_security_applications_get_all:
    pattern: /user/applications
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserApplications:getAll }
    methods: [GET]

pp_security_applications_get:
    pattern: /user/applications/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserApplications:get }
    methods: [GET]
    requirements:
        id: \d+

# Tokens
pp_security_tokens_get_all:
    pattern: /user/tokens
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:getAll }
    methods: [GET]

pp_security_tokens_get:
    pattern: /user/tokens/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:get }
    methods: [GET]
    requirements:
        id: \d+

pp_security_token_post:
    pattern: /user/tokens
    defaults: { _controller: PropertyPrivatelySecurityBundle:UserTokens:post }
    methods: [POST]

# User
pp_security_user_get:
    pattern: /user
    defaults: { _controller: PropertyPrivatelySecurityBundle:User:get }
    methods: [GET]

# Users
pp_security_users_get:
    pattern: /users/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:Users:get }
    methods: [GET]
    requirements:
        id: \d+
