pp_security_token_get:
    pattern: /user/tokens/{id}
    defaults: { _controller: PropertyPrivatelySecurityBundle:Token:get }
    methods: [GET]
    requirements:
        id: \d+

pp_security_token_post:
    pattern: /user/tokens
    defaults: { _controller: PropertyPrivatelySecurityBundle:Token:post }
    methods: [POST]
