parameters:
    # Builders
    pp_security.token_builder.class: PropertyPrivately\SecurityBundle\Token\Builder\TokenBuilder
    pp_security.user_builder.class: PropertyPrivately\SecurityBundle\Entity\Builder\UserBuilder

    # Entities
    pp_security.application.class: PropertyPrivately\SecurityBundle\Entity\Application
    pp_security.role.class: PropertyPrivately\SecurityBundle\Entity\Role
    pp_security.token.class: PropertyPrivately\SecurityBundle\Entity\Token
    pp_security.user.class: PropertyPrivately\SecurityBundle\Entity\User

    # Gateways
    pp_security.token_gateway.class: PropertyPrivately\SecurityBundle\Gateway\TokenGateway

    # Generators
    pp_security.token_generator.class: PropertyPrivately\SecurityBundle\Token\Utils\TokenGenerator

    # Patchers
    pp_security.token_patcher.class: PropertyPrivately\SecurityBundle\Entity\Patcher\TokenPatcher
    pp_security.user_patcher.class: PropertyPrivately\SecurityBundle\Entity\Patcher\UserPatcher

    # Repos
    pp_security.application_repository.class: PropertyPrivately\SecurityBundle\Entity\Repository\ApplicationRepository
    pp_security.role_repository.class: Doctrine\ORM\EntityRepository
    pp_security.token_repository.class: PropertyPrivately\SecurityBundle\Entity\Repository\TokenRepository
    pp_security.user_repository.class: PropertyPrivately\SecurityBundle\Entity\Repository\UserRepository

    # Resource Assemblers
    # Applications
    pp_security.resource_assembler.applications.directory_assembler.class: PropertyPrivately\SecurityBundle\Resource\Assembler\Applications\DirectoryResourceAssembler
    pp_security.resource_assembler.applications.get_assembler.class: PropertyPrivately\SecurityBundle\Resource\Assembler\Applications\GetResourceAssembler
    # Users
    pp_security.resource_assembler.users.directory_assembler.class: PropertyPrivately\SecurityBundle\Resource\Assembler\Users\DirectoryResourceAssembler
    pp_security.resource_assembler.users.get_assembler.class: PropertyPrivately\SecurityBundle\Resource\Assembler\Users\GetResourceAssembler
    # User
    pp_security.resource_assembler.user.get_assembler.class: PropertyPrivately\SecurityBundle\Resource\Assembler\User\GetResourceAssembler
    # User Applications
    pp_security.resource_assembler.user_applications.get_all_assembler.class: PropertyPrivately\SecurityBundle\Resource\Assembler\UserApplications\GetAllResourceAssembler
    # User Tokens
    pp_security.resource_assembler.user_tokens.get_all_assembler.class: PropertyPrivately\SecurityBundle\Resource\Assembler\UserTokens\GetAllResourceAssembler
    pp_security.resource_assembler.user_tokens.get_assembler.class: PropertyPrivately\SecurityBundle\Resource\Assembler\UserTokens\GetResourceAssembler

    # Security
    pp_security.user_provider.class: PropertyPrivately\SecurityBundle\User\UserProvider
    pp_security.apikey_user_provider.class: PropertyPrivately\SecurityBundle\User\ApiKeyUserProvider
    pp_security.apikey_authenticator.class: PropertyPrivately\SecurityBundle\Authentication\ApiKeyAuthenticator
    pp_security.apikey_authenticated_voter.class: PropertyPrivately\SecurityBundle\Authorization\Voter\ApiKeyAuthenticatedVoter

    # Validators
    pp_security.user_validator.class: PropertyPrivately\SecurityBundle\Validator\UserValidator

services:
    # Builders
    pp_security.token_builder:
        class: %pp_security.token_builder.class%
        arguments:
            - "@pp_security.application_repository"
            - "@pp_security.token_repository"
            - "@pp_security.user_repository"
            - "@pp_security.user_validator"
            - "@pp_security.token_generator"

    pp_security.user_builder:
        class: %pp_security.user_builder.class%
        arguments:
            - "@security.encoder_factory"

    # Gateways
    pp_security.token_gateway:
        class: %pp_security.token_gateway.class%
        arguments:
            conn: '@doctrine.dbal.default_connection'

    # Generators
    pp_security.token_generator:
        class: %pp_security.token_generator.class%

    # Patcher
    pp_security.token_patcher:
        class: %pp_security.token_patcher.class%

    pp_security.user_patcher:
        class: %pp_security.user_patcher.class%

    # Repos
    pp_security.application_repository:
        class: %pp_security.application_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %pp_security.application.class%

    pp_security.role_repository:
        class: %pp_security.role_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %pp_security.role.class%

    pp_security.token_repository:
        class: %pp_security.token_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %pp_security.token.class%

    pp_security.user_repository:
        class: %pp_security.user_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %pp_security.user.class%

    # Resource Assemblers
    # Applications
    pp_security.resource_assembler.applications.directory_assembler:
        class: %pp_security.resource_assembler.applications.directory_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    pp_security.resource_assembler.applications.get_assembler:
        class: %pp_security.resource_assembler.applications.get_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # Users
    pp_security.resource_assembler.users.directory_assembler:
        class: %pp_security.resource_assembler.users.directory_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    pp_security.resource_assembler.users.get_assembler:
        class: %pp_security.resource_assembler.users.get_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # User
    pp_security.resource_assembler.user.get_assembler:
        class: %pp_security.resource_assembler.user.get_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # User Applications
    pp_security.resource_assembler.user_applications.get_all_assembler:
        class: %pp_security.resource_assembler.user_applications.get_all_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # User Tokens
    pp_security.resource_assembler.user_tokens.get_all_assembler:
        class: %pp_security.resource_assembler.user_tokens.get_all_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    pp_security.resource_assembler.user_tokens.get_assembler:
        class: %pp_security.resource_assembler.user_tokens.get_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # Security
    pp_security.user_provider:
        class: %pp_security.user_provider.class%
        arguments:
            - "@pp_security.user_repository"

    pp_security.apikey_user_provider:
        class: %pp_security.apikey_user_provider.class%
        arguments:
            - "@pp_security.user_provider"
            - "@pp_security.application_repository"
            - "@pp_security.token_repository"

    pp_security.apikey_authenticator:
        class: %pp_security.apikey_authenticator.class%
        arguments:
            - "@pp_security.apikey_user_provider"

    pp_security.apikey_authenticated_voter:
        class: %pp_security.apikey_authenticated_voter.class%
        arguments:
            - "@security.authentication.trust_resolver"
        public:     false
        tags:
            - { name: security.voter }

    # Validator
    pp_security.user_validator:
        class: %pp_security.user_validator.class%
        arguments:
            - "@security.encoder_factory"
