parameters:
    # HAL
    seer_uk_rest.hal_root_resource_factory.class: SeerUK\RestBundle\Hal\Factory\RootResourceFactory
    seer_uk_rest.hal_root_resource.class: SeerUK\RestBundle\Hal\Resource\Resource

services:
    seer_uk_rest.listener.exception_listener:
        class: SeerUK\RestBundle\EventListener\ExceptionListener
        arguments:
            response: '@seer_uk_rest.hal_root_resource_factory'
            logger: '@logger'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    seer_uk_rest.api_doc.extractor.json_request_annotation_handler:
        class: SeerUK\RestBundle\AnnotationHandler\JsonRequestAnnotationHandler
        tags:
            - { name: nelmio_api_doc.extractor.handler }

    # HAL
    seer_uk_rest.hal_root_resource_factory:
        class: "%seer_uk_rest.hal_root_resource_factory.class%"
        arguments:
            - '@request_stack'
            - '@router'

    seer_uk_rest.hal_root_resource:
        class: "%seer_uk_rest.hal_root_resource.class%"
        factory_service: seer_uk_rest.hal_root_resource_factory
        factory_method: build
