parameters:
#    seer_uk_rest.example.class: SeerUK\RestBundle\Example

services:
#    seer_uk_rest.example:
#        class: %seer_uk_rest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
