property_privately_directory_index:
    pattern:  /
    defaults: { _controller: PropertyPrivatelyDirectoryBundle:Directory:index }

property_privately_directory_embedded_test:
    pattern:  /embedded
    defaults: { _controller: PropertyPrivatelyDirectoryBundle:Directory:embeddedTest }