property_privately_directory_index:
    pattern:  /v1
    defaults: { _controller: PropertyPrivatelyDirectoryBundle:Directory:index }

property_privately_directory_user_test:
    pattern:  /v1/users
    defaults: { _controller: PropertyPrivatelyDirectoryBundle:Directory:userTest }

property_privately_directory_view_user_test:
    pattern:  /v1/user/login
    defaults: { _controller: PropertyPrivatelyDirectoryBundle:Directory:userLoginTest }