parameters:
#    property_privately_directory.example.class: PropertyPrivately\DirectoryBundle\Example

services:
#    property_privately_directory.example:
#        class: %property_privately_directory.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
