parameters:
    pp_directory.user_test_resource_assembler.class: PropertyPrivately\DirectoryBundle\Resource\Assembler\Directory\UserTestResourceAssembler

services:
    pp_directory.user_test_resource_assembler:
        class: %pp_directory.user_test_resource_assembler.class%
        arguments:
            - '@router'
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]
