PropertyPrivately\PropertyBundle\Entity\Address:
    type: entity
    table: Address
    indexes:
        propertyId:
            columns:
                - propertyId
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        buildingname:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: buildingName
        address1:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        address2:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        town:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        postcode:
            type: string
            nullable: true
            length: 7
            fixed: false
            comment: ''
        lastmodified:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: lastModified
    manyToOne:
        propertyid:
            targetEntity: Property
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                propertyId:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
