PropertyPrivately\PropertyBundle\Entity\Property:
    type: entity
    table: Property
    indexes:
        userId:
            columns:
                - userId
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        description:
            type: string
            nullable: false
            length: 1000
            fixed: false
            comment: ''
        lastmodified:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: lastModified
    manyToOne:
        userid:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                userId:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
