PropertyPrivately\PropertyBundle\Entity\Roomtype:
    type: entity
    table: RoomType
    uniqueConstraints:
        name:
            columns:
                - name
        ref:
            columns:
                - ref
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        ref:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        description:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        lastmodified:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: lastModified
    lifecycleCallbacks: {  }
