# Properties
pp_property_properties_directory:
    pattern: /properties
    defaults: { _controller: PropertyPrivatelyPropertyBundle:Properties:directory }
    methods: [GET]

pp_property_properties_get:
    pattern: /properties/{id}
    defaults: { _controller: PropertyPrivatelyPropertyBundle:Properties:get }
    methods: [GET]
    requirements:
        id: \d+

# Properties Images
pp_property_properties_images_get_all:
    pattern: /properties/{propId}/images
    defaults: { _controller: PropertyPrivatelyPropertyBundle:PropertiesImages:getAll }
    methods: [GET]
    requirements:
        propId: \d+

pp_property_properties_images_get:
    pattern: /properties/{propId}/images/{imageId}
    defaults: { _controller: PropertyPrivatelyPropertyBundle:PropertiesImages:get }
    methods: [GET]
    requirements:
        propId: \d+
        imageId: \d+

# User Properties
pp_property_user_properties_get_all:
    pattern: /user/properties
    defaults: { _controller: PropertyPrivatelyPropertyBundle:UserProperties:getAll }
    methods: [GET]

pp_property_user_properties_get:
    pattern: /user/properties/{id}
    defaults: { _controller: PropertyPrivatelyPropertyBundle:UserProperties:get }
    methods: [GET]
    requirements:
        id: \d+

pp_property_user_properties_post:
    pattern: /user/properties
    defaults: { _controller: PropertyPrivatelyPropertyBundle:UserProperties:post }
    methods: [POST]

pp_property_user_properties_patch:
    pattern: /user/properties/{id}
    defaults: { _controller: PropertyPrivatelyPropertyBundle:UserProperties:patch }
    methods: [PATCH]
    requirements:
        id: \d+

pp_property_user_properties_delete:
    pattern: /user/properties/{id}
    defaults: { _controller: PropertyPrivatelyPropertyBundle:UserProperties:delete }
    methods: [DELETE]
    requirements:
        id: \d+

# User Properties Images
pp_property_user_properties_images_get_all:
    pattern: /user/properties/{propId}/images
    defaults: { _controller: PropertyPrivatelyPropertyBundle:UserPropertiesImages:getAll }
    methods: [GET]
    requirements:
        propId: \d+

pp_property_user_properties_images_get:
    pattern: /user/properties/{propId}/images/{imageId}
    defaults: { _controller: PropertyPrivatelyPropertyBundle:UserPropertiesImages:get }
    methods: [GET]
    requirements:
        propId: \d+
        imageId: \d+

pp_property_user_properties_images_post:
    pattern: /user/properties/{propId}/images
    defaults: { _controller: PropertyPrivatelyPropertyBundle:UserPropertiesImages:post }
    methods: [POST]
    requirements:
        propId: \d+

pp_property_user_properties_images_patch:
    pattern: /user/properties/{propId}/images/{imageId}
    defaults: { _controller: PropertyPrivatelyPropertyBundle:UserPropertiesImages:patch }
    methods: [PATCH]
    requirements:
        propId: \d+
        imageId: \d+

pp_property_user_properties_images_delete:
    pattern: /user/properties/{propId}/images/{imageId}
    defaults: { _controller: PropertyPrivatelyPropertyBundle:UserPropertiesImages:delete }
    methods: [DELETE]
    requirements:
        propId: \d+
        imageId: \d+