parameters:
    # Entities
    pp_property.image.class: PropertyPrivately\PropertyBundle\Entity\Image
    pp_property.offer.class: PropertyPrivately\PropertyBundle\Entity\Offer
    pp_property.property.class: PropertyPrivately\PropertyBundle\Entity\Property
    pp_property.sale.class: PropertyPrivately\PropertyBundle\Entity\Sale

    # Repos
    pp_property.image_repository.class: PropertyPrivately\PropertyBundle\Entity\Repository\ImageRepository
    pp_property.offer_repository.class: PropertyPrivately\PropertyBundle\Entity\Repository\OfferRepository
    pp_property.property_repository.class: PropertyPrivately\PropertyBundle\Entity\Repository\PropertyRepository
    pp_property.sale_repository.class: PropertyPrivately\PropertyBundle\Entity\Repository\SaleRepository

    # Resource Assemblers
    # Properties
    pp_property.resource_assembler.properties.directory_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\Properties\DirectoryResourceAssembler
    pp_property.resource_assembler.properties.get_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\Properties\GetResourceAssembler
    # Properties Images
    pp_property.resource_assembler.properties_images.get_all_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\PropertiesImages\GetAllResourceAssembler
    pp_property.resource_assembler.properties_images.get_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\PropertiesImages\GetResourceAssembler
    # Properties Sales
    pp_property.resource_assembler.properties_sales.get_all_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\PropertiesSales\GetAllResourceAssembler
    pp_property.resource_assembler.properties_sales.get_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\PropertiesSales\GetResourceAssembler
    # Sales
    pp_property.resource_assembler.sales.directory_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\Sales\DirectoryResourceAssembler
    pp_property.resource_assembler.sales.get_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\Sales\GetResourceAssembler
    # Sales Offers
    pp_property.resource_assembler.sales_offers.get_all_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\SalesOffers\GetAllResourceAssembler
    pp_property.resource_assembler.sales_offers.get_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\SalesOffers\GetResourceAssembler
    # User Properties
    pp_property.resource_assembler.user_properties.get_all_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\UserProperties\GetAllResourceAssembler
    # Users Sale
    pp_property.resource_assembler.user_sales.get_all_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\UserSales\GetAllResourceAssembler
    # Users Sales
    pp_property.resource_assembler.users_sales.get_all_assembler.class: PropertyPrivately\PropertyBundle\Resource\Assembler\UsersSales\GetAllResourceAssembler

services:
    # Repos
    pp_property.image_repository:
        class: %pp_property.image_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %pp_property.image.class%

    pp_property.offer_repository:
        class: %pp_property.offer_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %pp_property.offer.class%

    pp_property.property_repository:
        class: %pp_property.property_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %pp_property.property.class%

    pp_property.sale_repository:
        class: %pp_property.sale_repository.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %pp_property.sale.class%

    # Resource Assemblers
    # Properties
    pp_property.resource_assembler.properties.directory_assembler:
        class: %pp_property.resource_assembler.properties.directory_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    pp_property.resource_assembler.properties.get_assembler:
        class: %pp_property.resource_assembler.properties.get_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # Properties Images
    pp_property.resource_assembler.properties_images.get_all_assembler:
        class: %pp_property.resource_assembler.properties_images.get_all_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    pp_property.resource_assembler.properties_images.get_assembler:
        class: %pp_property.resource_assembler.properties_images.get_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # Properties Sales
    pp_property.resource_assembler.properties_sales.get_all_assembler:
        class: %pp_property.resource_assembler.properties_sales.get_all_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    pp_property.resource_assembler.properties_sales.get_assembler:
        class: %pp_property.resource_assembler.properties_sales.get_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # Sales
    pp_property.resource_assembler.sales.directory_assembler:
        class: %pp_property.resource_assembler.sales.directory_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    pp_property.resource_assembler.sales.get_assembler:
        class: %pp_property.resource_assembler.sales.get_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # Sales Offers
    pp_property.resource_assembler.sales_offers.get_all_assembler:
        class: %pp_property.resource_assembler.sales_offers.get_all_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    pp_property.resource_assembler.sales_offers.get_assembler:
        class: %pp_property.resource_assembler.sales_offers.get_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # User Properties
    pp_property.resource_assembler.user_properties.get_all_assembler:
        class: %pp_property.resource_assembler.user_properties.get_all_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # User Sales
    pp_property.resource_assembler.user_sales.get_all_assembler:
        class: %pp_property.resource_assembler.user_sales.get_all_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]

    # Users Sales
    pp_property.resource_assembler.users_sales.get_all_assembler:
        class: %pp_property.resource_assembler.users_sales.get_all_assembler.class%
        arguments:
            - "@router"
        calls:
            - [setRootResource, ["@seer_uk_rest.hal_root_resource"]]
