parameters:
#    property_privately_core.example.class: PropertyPrivately\CoreBundle\Example

services:
#    property_privately_core.example:
#        class: %property_privately_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
