property_privately_core:
    resource: "@PropertyPrivatelyCoreBundle/Resources/config/routing.yml"
    prefix:   /

property_privately_security:
    resource: "@PropertyPrivatelySecurityBundle/Resources/config/routing.yml"
    prefix:   /

property_privately_directory:
    resource: "@PropertyPrivatelyDirectoryBundle/Resources/config/routing.yml"
    prefix:   /

seer_uk_rest:
    resource: "@SeerUKRestBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
