property_privately_security:
    resource: "@PropertyPrivatelySecurityBundle/Resources/config/routing.yml"
    prefix:   /

property_privately_directory:
    resource: "@PropertyPrivatelyDirectoryBundle/Resources/config/routing.yml"
    prefix:   /

seer_uk_rest:
    resource: "@SeerUKRestBundle/Resources/config/routing.yml"
    prefix:   /

